[package]
name = "Tutorial"
version = "0.0.1"

[dependencies]
MoveStdlib = { local = "../../../crates/sui-framework/deps/move-stdlib/" }
Sui = { local = "../../../crates/sui-framework/" }

[addresses]
Tutorial = "0x0"

