# These are supported funding model platforms

github: firedlcoud # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: okand # Replace with a single Patreon username
open_collective: really # Replace with a single Open Collective username
ko_fi: woozy # Replace with a single Ko-fi username
tidelift: tidel # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: sussy # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: qwerty # Replace with a single Liberapay username
issuehunt: cringe # Replace with a single IssueHunt username
otechie: coolapp # Replace with a single Otechie username
lfx_crowdfunding: beloved # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['https://example.com/some-url', 'xmr:1234...abcd', "fkjdgdfklgjdfsklgjdfsklgdf, "dffdfdfsdfsdf, "dffghjhygthgh"] # Replace with up to 4 custom sponsorship URLs e.g., ['https://example.com/some-url', 'xmr:1234...abcd'
