[package]
name = "sui-json"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { version = "1.0.57", features = ["backtrace"] }
bcs = "0.1.3"
hex = "0.4.3"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.79"
schemars = "0.8.8"

sui-types = { path = "../sui-types" }
sui-verifier = { path = "../sui-verifier" }

move-binary-format = { git = "https://github.com/move-language/move", rev = "1b2d3b4274345f5b4b6a1a1bde5aee452003ab5b" }
move-core-types = { git = "https://github.com/move-language/move", rev = "1b2d3b4274345f5b4b6a1a1bde5aee452003ab5b", features = ["address20"] }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
test-fuzz = "3.0.2"

sui-adapter = { path = "../sui-adapter" }
sui-framework = { path = "../sui-framework" }
