name: Explorer Client PR checks
on: pull_request
jobs:
  diff:
    runs-on: [ubuntu-latest]
    outputs:
      isClient: ${{ steps.diff.outputs.isExplorerClient }}
    steps:
      - uses: actions/checkout@v3
      - name: Detect Changes
        uses: "./.github/actions/diffs"
        id: diff
  client_checks:
    name: Lint, Test & Build
    needs: diff
    if: needs.diff.outputs.isClient == 'true'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: ./explorer/client/yarn.lock
      - name: Build TS sdk
        working-directory: ./sdk/typescript
        run: yarn install; yarn build
      - name: Install yarn dependencies
        working-directory: ./explorer/client
        run: yarn install --force
      - name: Lint
        working-directory: ./explorer/client
        run: yarn lint
      - name: Test
        working-directory: ./explorer/client
        run: yarn test
      - name: Build
        working-directory: ./explorer/client
        run: yarn build
