[package]
name = "sui-types"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { version = "1.0.57", features = ["backtrace"] }
bcs = "0.1.3"
bincode = "1.3.3"
itertools = "0.10.3"
once_cell = "1.11.0"
rand = "0.7.3"
serde = { version = "1.0.137", features = ["derive"] }
ed25519-dalek = { version = "1.0.1", features = ["batch", "serde"] }
curve25519-dalek = { version = "3", default-features = false, features = ["serde"] }
serde-name = "0.2.1"
sha3 = "0.10.1"
thiserror = "1.0.31"
hex = "0.4.3"
serde_bytes = "0.11.6"
serde_json = "1.0.80"
serde_with = "1.14.0"
signature = "1.5.0"
static_assertions = "1.1.0"
opentelemetry = { version = "0.17.0", features = ["rt-tokio"] }
parking_lot = "0.12.1"
base64ct = { version = "1.5.0", features = ["alloc"] }
sha2 = "0.10.2"
zeroize = "1.5.4"
hkdf = "0.12.3"
digest = "0.10.3"
schemars ="0.8.10"
tonic = "0.7"
strum_macros = "^0.24"

name-variant = { git = "https://github.com/MystenLabs/mysten-infra", rev = "ff5c1d69057fe93be658377462ca2875a57a0223" }
typed-store = { git = "https://github.com/MystenLabs/mysten-infra", rev = "ff5c1d69057fe93be658377462ca2875a57a0223" }

move-binary-format = { git = "https://github.com/move-language/move", rev = "1b2d3b4274345f5b4b6a1a1bde5aee452003ab5b" }
move-bytecode-utils = { git = "https://github.com/move-language/move", rev = "1b2d3b4274345f5b4b6a1a1bde5aee452003ab5b" }
move-core-types = { git = "https://github.com/move-language/move", rev = "1b2d3b4274345f5b4b6a1a1bde5aee452003ab5b", features = ["address20"] }
move-disassembler = { git = "https://github.com/move-language/move", rev = "1b2d3b4274345f5b4b6a1a1bde5aee452003ab5b" }
move-ir-types = { git = "https://github.com/move-language/move", rev = "1b2d3b4274345f5b4b6a1a1bde5aee452003ab5b" }
move-vm-types = { git = "https://github.com/move-language/move", rev = "1b2d3b4274345f5b4b6a1a1bde5aee452003ab5b" }

narwhal-executor = { git = "https://github.com/MystenLabs/narwhal", rev = "2c5e8236c0702a3ff47dd769c2bbc94b029bf4a9", package = "executor" }
narwhal-crypto = { git = "https://github.com/MystenLabs/narwhal", rev = "2c5e8236c0702a3ff47dd769c2bbc94b029bf4a9", package = "crypto" }
workspace-hack = { path = "../workspace-hack"}
