[package]
name = "sui-open-rpc"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
schemars = "0.8.10"
serde = "1.0.136"
workspace-hack = { path = "../workspace-hack"}
