[package]
name = "test-utils"
authors = ["Mysten Labs <build@mystenlabs.com>"]
version = "0.1.0"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { version = "1.0.57", features = ["backtrace"] }
tokio = { version = "1.18.2", features = ["sync", "rt"] }
tokio-util = { version = "0.7.2", features = ["codec"] }
bytes = "1.1.0"
futures = "0.3.21"
async-trait = "0.1.53"
rand = "0.7.3"
rocksdb = "0.18.0"
tracing = "0.1.34"
tempfile = "3.3.0"
bcs = "0.1.3"
jsonrpsee-http-server = "0.13.1"
jsonrpsee-http-client = "0.13.1"

sui-adapter = { path = "../sui-adapter" }
sui-framework = { path = "../sui-framework" }
sui-gateway = { path = "../sui-gateway" }
move-package = { git = "https://github.com/move-language/move", rev = "1b2d3b4274345f5b4b6a1a1bde5aee452003ab5b" }
move-core-types = { git = "https://github.com/move-language/move", rev = "1b2d3b4274345f5b4b6a1a1bde5aee452003ab5b", features = ["address20"] }
typed-store = { git = "https://github.com/MystenLabs/mysten-infra", rev ="ff5c1d69057fe93be658377462ca2875a57a0223"}
narwhal-config = { git = "https://github.com/MystenLabs/narwhal", rev = "2c5e8236c0702a3ff47dd769c2bbc94b029bf4a9", package = "config" }

sui-config = { path = "../sui-config" }
sui-types = { path = "../sui-types" }
sui-core = { path = "../sui-core" }
sui-network = { path = "../sui-network" }
sui-node = { path = "../sui-node" }
sui-swarm = { path = "../sui-swarm" }
sui = { path = "../sui" }
workspace-hack = { path = "../workspace-hack"}
