[package]
name = "sui-config"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
bcs = "0.1.3"
anyhow = { version = "1.0.57", features = ["backtrace"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_yaml = "0.8.23"
base64ct = { version = "1.5.0", features = ["alloc"] }
rand = "0.7.3"
dirs = "4.0.0"
multiaddr = "0.14.0"
once_cell = "1.11.0"
debug-ignore = { version = "1.0.2", features = ["serde"] }
tracing = "0.1.34"

narwhal-config = { git = "https://github.com/MystenLabs/narwhal", rev = "2c5e8236c0702a3ff47dd769c2bbc94b029bf4a9", package = "config" }
narwhal-crypto = { git = "https://github.com/MystenLabs/narwhal", rev = "2c5e8236c0702a3ff47dd769c2bbc94b029bf4a9", package = "crypto" }
move-binary-format = { git = "https://github.com/move-language/move", rev = "1b2d3b4274345f5b4b6a1a1bde5aee452003ab5b" }
move-package = { git = "https://github.com/move-language/move", rev = "1b2d3b4274345f5b4b6a1a1bde5aee452003ab5b" }

sui-framework = { path = "../sui-framework" }

sui-adapter = { path = "../sui-adapter" }
sui-types = { path = "../sui-types" }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
tempfile = "3.3.0"
