[package]
name = "sui-cluster-test"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
futures = "0.3.21"
serde_json = "1.0.80"
tempfile = "3.3.0"
tokio = { version = "1.17.0", features = ["full"] }
async-trait = "0.1.53"
serde_with = { version = "1.13.0", features = ["hex"] }
tracing = { version = "0.1.34", features = ["log"] }
clap = { version = "3.1.14", features = ["derive"] }
reqwest = { version = "0.11.10", features = ["blocking", "json"] }
telemetry-subscribers = { git = "https://github.com/MystenLabs/mysten-infra", rev = "ff5c1d69057fe93be658377462ca2875a57a0223" }

sui-faucet = { path = "../sui-faucet" }
sui = { path = "../sui" }
sui-core = { path = "../sui-core" }
sui-types = { path = "../sui-types" }
sui-json = { path = "../sui-json" }
workspace-hack = { path = "../workspace-hack"}