[package]
name = "sui-storage"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.55"
async-trait = "0.1.53"
fdlimit = "0.2.1"
futures = "0.3.21"
flexstr = "^0.9"
rand = "0.7.3"
serde = { version = "1.0.136", features = ["derive"] }
tokio = { version = "1.17.0", features = ["full", "tracing"] }
rocksdb = "0.18.0"
tracing = "0.1.34"

sui-types = { path = "../sui-types" }

typed-store = { git = "https://github.com/MystenLabs/mysten-infra", rev = "ff5c1d69057fe93be658377462ca2875a57a0223"}
workspace-hack = { path = "../workspace-hack"}

move-core-types = { git = "https://github.com/move-language/move", rev = "1b2d3b4274345f5b4b6a1a1bde5aee452003ab5b", features = ["address20"] }

[dev-dependencies]
tempfile = "3.3.0"
num_cpus = "1.13.1"
pretty_assertions = "1.2.0"
telemetry-subscribers = { git = "https://github.com/MystenLabs/mysten-infra", rev = "ff5c1d69057fe93be658377462ca2875a57a0223" }

[[bench]]
name = "write_ahead_log"
harness = false
