name: Create New Issue

on: [push, pull_request, workflow_dispatch, schedule, deployment, issue_comment]

jobs:
  create_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Latest Issue Number
        id: get_latest_issue
        run: |
          latest_issue_number=$(curl -sH "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                              "https://api.github.com/repos/${{ github.repository }}/issues?state=all&sort=created&direction=desc" \
                              | jq -r '.[0].number')
          echo "::set-output name=latest_issue_number::$latest_issue_number"

      - name: Create New Issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Issue ${{ steps.get_latest_issue.outputs.latest_issue_number }}
          content-filepath: ./issue_template.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
